### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by Messer262a** [explooosion/Agm-Direction#10]
Angular 5.2.2 . Not AoT.

ERROR in [at-loader] ./node_modules/@angular/core/src/render3/ng_dev_mode.d.ts:9:11
    TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ERROR in [at-loader] ./node_modules/agm-direction/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts:9:11
    TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

Temporarily solved this by downgrading to angular 5.1.3 as suggested here
https://github.com/angular/angular/issues/21670#issuecomment-370274821

Author of ngx-paypal also had this issue and fixed it by refactoring his code
https://github.com/Enngage/ngx-paypal/issues/1

Also, got this AoT error after going down to ng 5.1.3
ERROR in agm-direction\src\agm-direction.module.ts(4,2): Error during template compile of 'AgmDirectionModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by explooosion** [comment]
Hi! @Messer262a 
I have upgraded the package. https://github.com/explooosion/Agm-Direction/issues/9#issuecomment-373907053
