### ISSUE TITLE
How to show multiple directions to points (A, B, C, D) etc. 

### ISSUE THREAD

**Issue by Brenton30** [explooosion/Agm-Direction#11]
`          <agm-map class="map" [latitude]="plan.Lat" [longitude]="plan.Lng">
              <agm-direction *ngFor="let a of dayRoute" [origin]="a.origin" [destination]="a.dest" [travelMode]="a.mode.toUpperCase()"></agm-direction>
          </agm-map>`

Which shows this: 

![capture](https://user-images.githubusercontent.com/28558058/37529806-f6f014da-292f-11e8-9749-ccb6547e90a1.PNG)

However, I want it to show the points separately as A, B, C, D etc in order?

**Comment by thari119** [comment]
how did u fix this @Brenton30
