### ISSUE TITLE
"provideRouteAlternatives" not implemented

### ISSUE THREAD

**Issue by NeelamVagal** [explooosion/Agm-Direction#12]
![image](https://user-images.githubusercontent.com/2353589/38491419-a884553a-3ba0-11e8-8ed1-aff43ca7e059.png)

**Comment by explooosion** [comment]
Hi! @NeelamVagal.  I have upgraded the package (**Version 0.4.2**).
Please install the latest version:
```bash
npm install agm-direction@latest
```


You can set the `provideRouteAlternatives` to your direction.

+ HTML
```html
  <agm-direction .. [provideRouteAlternatives]="alternatives"></agm-direction>
```

+ TS
```ts
  alternatives = true;
```

### Reference
[Directions Requests](https://developers.google.com/maps/documentation/javascript/directions?hl=en#DirectionsRequests)

**Comment by NeelamVagal** [comment]
Thanks a lot for such prompt action! It works now :)
