### ISSUE TITLE
push waypoints not working

### ISSUE THREAD

**Issue by lolaswift** [explooosion/Agm-Direction#14]
Thx for the nice directive. Can you please help me?

<agm-map [latitude]="lat" [longitude]="lng" [scrollwheel]="false" [zoom]="zoom">
                <agm-direction *ngIf="dir" [origin]="dir.origin" [destination]="dir.destination" [waypoints]="stopoversCoords" [optimizeWaypoints]="true"></agm-direction>
              </agm-map>

I am trying to add waypoints dynamically by pushing a waypoint to the array, it doesn't work:
    let myLat = place.geometry.location.lat();
    let myLng = place.geometry.location.lng();
    this.stopoversCoords.push({ location: { lat: myLat, lng: myLng }, stopover: true });

If I do:
  this.stopoversCoords = [{ location: { lat: myLat, lng: myLng }, stopover: true }];
it works.

**Comment by explooosion** [comment]
Hi @lolaswift  

Because `ngOnChanges ` event needs the new object. so we have to give the waypoint a new array.

Use the following example:
```ts
const waypoints = Object.create(this.waypoints)
waypoints.push({
  location: { lat: myLat, lng: myLng },
  stopover: true,
})
this.waypoints = waypoints
```

Or the better way:
+ [Array.prototype.concat()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

```ts
this.waypoints = this.waypoints.concat({
  location: { lat: myLat, lng: myLng },
  stopover: true,
})
```

**Comment by explooosion** [comment]
It’s my pleasure. 😉

**Comment by Joni-89** [comment]
Hi,
I need to switch position in the waypoint array. I try to create a new array and push into the waypoint but the route is not re drawing.
I have an array "tripDestinations" where i m saving the waypoints and the last record is the final destination. So i have to split the destinations after a change on the array.

Here is part of my code:

A function to switch dynamically destinations:

  move(index: number, up: boolean) {
    const newIndex = up ? index - 1 : index + 1;
    while (index < 0) {
      index += this.tripDestinations.length;
    }
    while (index < 0) {
      index += this.tripDestinations.length;
    }

    if (newIndex >= this.tripDestinations.length) {
      let k = newIndex - this.tripDestinations.length + 1;
      while (k--) {
        this.tripDestinations.push(undefined);
      }
    }
    this.tripDestinations.splice(newIndex, 0, this.tripDestinations.splice(index, 1)[0]);
    this.showRoute();
  }

The function that i get the "final destination" and the waypoints:

showRoute(){
      this.origin = { lat: this.latitudeOrigin, lng: this.longitudeOrigin };
      const length = this.tripDestinations.length;
      this.destination = { lat: this.tripDestinations[length - 1].latitude, lng: this.tripDestinations[length - 1].longitude };

      if (length > 1) {
        const waypoints: any[] = [];
        for (let index = 0; index < length - 1; index++) {
          waypoints.push({
            location: { lat: this.tripDestinations[index].latitude, lng: this.tripDestinations[index].longitude }
          });
          }
        this.waypoints = waypoints;
}
}
HTML:
<agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom">                                  
<agm-direction [origin]="origin" [destination]="destination" [waypoints]="waypoints" [renderOptions]="renderOptions">
</agm-direction>
</agm-map>

Example:
Original waypoint array:
[{"location":{"lat":-34.6048436,"lng":-58.40282109999998}},{"location":{"lat":-34.6173554,"lng":-58.38177689999998}}]

After using the "move()" function, i get this waypoint array in the showRoute():
[{"location":{"lat":-34.6173554,"lng":-58.38177689999998}},{"location":{"lat":-34.6048436,"lng":-58.40282109999998}}]

Thx in advance
