### ISSUE TITLE
Need to change the Icons of origin and destination

### ISSUE THREAD

**Issue by udaygowda** [explooosion/Agm-Direction#15]
Hi,

I need to change the icons(different icons) and add info window to both origin and destination.

![image](https://user-images.githubusercontent.com/1020104/39051103-53808c2e-44c5-11e8-9d3c-f5d1216a2e9e.png)

Help me on how to do this.

Thanks
Uday

**Comment by explooosion** [comment]
Hi! @udaygowda ! 
I have upgraded the package, please install the latest version ^0.5.2.

### Example:

HTML

```html
<agm-direction ... [renderOptions]="renderOpts" [markerOptions]="markerOpts"></agm-direction>
```

TS

[MarkerOptions object specification](https://developers.google.com/maps/documentation/javascript/reference?hl=zh-tw#MarkerOptions)

```ts
renderOpts = {
  suppressMarkers: true,
};

markerOpts = {
  origin: {
    icon: 'your-icon-url',
  },
  destination: {
    icon: 'your-icon-url',
    label: 'marker label',
    opacity: 0.8,
    // ... properties
  },
};
```

DEMO
![image](https://user-images.githubusercontent.com/13682994/39082494-8a4a030e-4586-11e8-8349-0353bcaabb93.png)

**Comment by udaygowda** [comment]
Thanks for the Feature update. It was very quick i appreciate your efforts.
