### ISSUE TITLE
Switch language?

### ISSUE THREAD

**Issue by 0190** [explooosion/Agm-Direction#16]
Hi there!

Need help - is there a way to switch configured language in runtime? I see that language is preconfigured in module declaration, which is unfortunate. Did I miss something by any chance? If not, how would you go about handling Google Maps API calls in different languages?

Thanks!

**Comment by 0190** [comment]
Wrong repo :)

In case anyone wondering, here's the answer: https://github.com/SebastianM/angular-google-maps/issues/1358

**Comment by lolaswift** [comment]
@0190 thx Maria
