### ISSUE TITLE
How to give names to the waypoints and origin destination instead of a,b,c..and separate color to origin marker

### ISSUE THREAD

**Issue by mohanbkrishna** [explooosion/Agm-Direction#17]
How can we give names to the way-points and origin destination instead of a,b,c..and separate color to origin marker?

Suppose I have 3 waypoints starting from abc office via john street, david colony, rome market street and reaches xyz home., I need to show all these names instead of a,b,c,d... and the 1st marker that is abc office should be in different color. I s it possible to show these. Thanks in advance

**Comment by mohanbkrishna** [comment]
And even I'm trying add icon,labels in markerOptions its not adding to origin/destination

**Comment by mohanbkrishna** [comment]
Basically we want to give names or change the a.b.c.d ..to 1,2,3,4.. for way points

**Comment by explooosion** [comment]
Hi, @mohanbkrishna ! 
Actually I've noticed and read your question last week. 
But now I am in a hard time with my work,  and please be patient and kind to wait for  me for some days , I will try my best to solve your problems as soon as possible. Thank you!

**Comment by mohanbkrishna** [comment]
Oh thanks for the response, take your time, I'm also trying to figure out in my way. If any luck from my side, I will let you know. And please try to give hints or suggest ways to figure out the issue as soon as you got some free time.

**Comment by explooosion** [comment]
#21

**Comment by monikagupta78** [comment]
I also have similar requirement to show specific names to the waypoints instead of A,B,C. Any pointers?

**Comment by explooosion** [comment]
Sorry for the late reply, please install the latest version.
You can give names to the waypoints and origin destination now.🙂

For example:

#### HTML

```html
<agm-map [latitude]="lat" [longitude]="lng">
  <agm-direction 
		[origin]="origin" 
		[destination]="destination" 
		[renderOptions]="renderOptions" 
		[markerOptions]="markerOptions"
    	[waypoints]="waypoints"
  >
  </agm-direction>
</agm-map>
```

#### TypeScript

```typescript

  public lat: Number = 24.799448;
  public lng: Number = 120.979021;

  public origin = { lat: 24.799448, lng: 120.979021 };
  public destination = { lat: 24.799524, lng: 120.975017 };
  public waypoints = [
    {
      location: { lat: 24.7950879, lng: 120.9784989 },
      stopover: false,
    },
    {
      location: { lat: 24.7941879, lng: 120.9785989 },
      stopover: false,
    }, {
      location: { lat: 24.7992879, lng: 120.9716989 },
      stopover: false,
    }
  ];

  public renderOptions = {
    suppressMarkers: true,
  };

  public markerOptions = {
    origin: {
      infoWindow: 'Origin.',
      icon: 'http://i.imgur.com/7teZKif.png',
    },
    waypoints: [
      {
        infoWindow: `<h4>A<h4>
        <a href='http://google.com' target='_blank'>A</a>
        `,
        icon: 'http://i.imgur.com/7teZKif.png',
      }, {
        infoWindow: `<h4>B<h4>
        <a href='http://google.com' target='_blank'>B</a>
        `,
        icon: 'http://i.imgur.com/7teZKif.png',
      },
      {
        infoWindow: `<h4>C<h4>
        <a href='http://google.com' target='_blank'>C</a>
        `,
        icon: 'http://i.imgur.com/7teZKif.png',
      }
    ],
    destination: {
      infoWindow: 'Destination',
      icon: 'http://i.imgur.com/7teZKif.png',
    },
  };
```

If your waypoints names and icons want to set all the same, you can follow the example:

```typescript
  public markerOptions = {
    origin: {
      infoWindow: 'Origin.',
      icon: 'http://i.imgur.com/7teZKif.png',
    },
    waypoints: {
      infoWindow: `<h4>A<h4>
      <a href='http://google.com' target='_blank'>A</a>
      `,
      icon: 'http://i.imgur.com/7teZKif.png',
    },
    destination: {
      infoWindow: 'Destination',
      icon: 'http://i.imgur.com/7teZKif.png',
    },
  };
```
```

**Comment by monikagupta78** [comment]
Thanks for the update. this will be really useful.

**Comment by qam12** [comment]
Thanks @explooosion

**Comment by asyf** [comment]
> Sorry for the late reply, please install the latest version.
> You can give names to the waypoints and origin destination now.🙂
> 
> For example:
> 
> #### HTML
> ```
> <agm-map [latitude]="lat" [longitude]="lng">
>   <agm-direction 
> 		[origin]="origin" 
> 		[destination]="destination" 
> 		[renderOptions]="renderOptions" 
> 		[markerOptions]="markerOptions"
>     	[waypoints]="waypoints"
>   >
>   </agm-direction>
> </agm-map>
> ```
> 
> #### TypeScript
> ```ts
>   public lat: Number = 24.799448;
>   public lng: Number = 120.979021;
> 
>   public origin = { lat: 24.799448, lng: 120.979021 };
>   public destination = { lat: 24.799524, lng: 120.975017 };
>   public waypoints = [
>     {
>       location: { lat: 24.7950879, lng: 120.9784989 },
>       stopover: false,
>     },
>     {
>       location: { lat: 24.7941879, lng: 120.9785989 },
>       stopover: false,
>     }, {
>       location: { lat: 24.7992879, lng: 120.9716989 },
>       stopover: false,
>     }
>   ];
> 
>   public renderOptions = {
>     suppressMarkers: true,
>   };
> 
>   public markerOptions = {
>     origin: {
>       infoWindow: 'Origin.',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     waypoints: [
>       {
>         infoWindow: `<h4>A<h4>
>         <a href='http://google.com' target='_blank'>A</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       }, {
>         infoWindow: `<h4>B<h4>
>         <a href='http://google.com' target='_blank'>B</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       },
>       {
>         infoWindow: `<h4>C<h4>
>         <a href='http://google.com' target='_blank'>C</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       }
>     ],
>     destination: {
>       infoWindow: 'Destination',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>   };
> ```
> 
> If your waypoints names and icons want to set all the same, you can follow the example:
> 
> ```ts
>   public markerOptions = {
>     origin: {
>       infoWindow: 'Origin.',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     waypoints: {
>       infoWindow: `<h4>A<h4>
>       <a href='http://google.com' target='_blank'>A</a>
>       `,
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     destination: {
>       infoWindow: 'Destination',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>   };
> ```

Hi what about with stopover true?

**Comment by explooosion** [comment]
Hi @asyf  !

You can Add stopover to waypoints.

```js
waypoints: [
    {
      icon: ...,
      infoWindow: ...,
      ...
      stopover: true
    },{
      ...
      stopover: true
}],
```

Ref: [https://developers.google.com/maps/documentation/javascript/directions#DirectionsRequests](https://developers.google.com/maps/documentation/javascript/directions#DirectionsRequests)

**Comment by asyf** [comment]
@explooosion i did that but that is not drawing markers.

**Comment by rbrijesh** [comment]
> Sorry for the late reply, please install the latest version.
> You can give names to the waypoints and origin destination now.
> 
> For example:
> 
> #### HTML
> ```
> <agm-map [latitude]="lat" [longitude]="lng">
>   <agm-direction 
> 		[origin]="origin" 
> 		[destination]="destination" 
> 		[renderOptions]="renderOptions" 
> 		[markerOptions]="markerOptions"
>     	[waypoints]="waypoints"
>   >
>   </agm-direction>
> </agm-map>
> ```
> 
> #### TypeScript
> ```ts
>   public lat: Number = 24.799448;
>   public lng: Number = 120.979021;
> 
>   public origin = { lat: 24.799448, lng: 120.979021 };
>   public destination = { lat: 24.799524, lng: 120.975017 };
>   public waypoints = [
>     {
>       location: { lat: 24.7950879, lng: 120.9784989 },
>       stopover: false,
>     },
>     {
>       location: { lat: 24.7941879, lng: 120.9785989 },
>       stopover: false,
>     }, {
>       location: { lat: 24.7992879, lng: 120.9716989 },
>       stopover: false,
>     }
>   ];
> 
>   public renderOptions = {
>     suppressMarkers: true,
>   };
> 
>   public markerOptions = {
>     origin: {
>       infoWindow: 'Origin.',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     waypoints: [
>       {
>         infoWindow: `<h4>A<h4>
>         <a href='http://google.com' target='_blank'>A</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       }, {
>         infoWindow: `<h4>B<h4>
>         <a href='http://google.com' target='_blank'>B</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       },
>       {
>         infoWindow: `<h4>C<h4>
>         <a href='http://google.com' target='_blank'>C</a>
>         `,
>         icon: 'http://i.imgur.com/7teZKif.png',
>       }
>     ],
>     destination: {
>       infoWindow: 'Destination',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>   };
> ```
> 
> If your waypoints names and icons want to set all the same, you can follow the example:
> 
> ```ts
>   public markerOptions = {
>     origin: {
>       infoWindow: 'Origin.',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     waypoints: {
>       infoWindow: `<h4>A<h4>
>       <a href='http://google.com' target='_blank'>A</a>
>       `,
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>     destination: {
>       infoWindow: 'Destination',
>       icon: 'http://i.imgur.com/7teZKif.png',
>     },
>   };
> ```

Thanks...

**Comment by havo07** [comment]
Hi @explooosion, i am install the latest version "0.7.9" and view not work this enhancement, i am use the next code:

public renderOptions = {
		draggable: true,
		suppressMarkers: true
	};

 public markerOptions = {
    origin: {
      icon: 'http://i.imgur.com/7teZKif.png',
    },
    waypoints: {
      icon: 'http://i.imgur.com/7teZKif.png',
    },
    destination: {
      icon: 'http://i.imgur.com/7teZKif.png',
    },
  };

**Comment by Hokino** [comment]
@rbrijesh 
Hi I am a little late to this. But did you ever figure out how to change markers reliably while having stopover set to true?
I need stopover to be true as it changes the color of my routes, but i also need to change the makers which can only happen if its set to false.
