### ISSUE TITLE
Remove agm-direction

### ISSUE THREAD

**Issue by aironpower** [explooosion/Agm-Direction#2]
Hi! I can't remove directions from the map. This is my html:
`<agm-map [fitBounds]="bounds" [latitude]="lat" [longitude]="lng" *ngIf="!clearMap" (change)=changeForm(confirm)>
	<div id="agmDirections" *ngFor="let shape of drawnLines; let i = index;">
		<agm-directions [origin]="shape.origin" [destination]="shape.destination" [waypoints]="shape.waypoints" [visible]="" (onShapes)="setShapes($event, shape)">
                </agm-directions>
	</div>
</agm-map>`
The direction is still displayed when I remove an element of the array 'drawnLines'.
I don't want to reload the map to do it, just not to see that direction.
Thank you in advance!

**Comment by explooosion** [comment]
Hi! I have upgraded an package .
  
#### Version: 
[![npm version](https://badge.fury.io/js/agm-direction.svg)](https://badge.fury.io/for/js/agm-direction)   
    
+ attribute (default)
visible: Boolean = true;  
  
#### Remove Example:

+ html 

```html
<agm-map [latitude]="lat" [longitude]="lng">
  <agm-direction *ngIf="dir" [origin]="dir.origin" [destination]="dir.destination" [visible]="show"></agm-direction>
</agm-map>

<button type="button" (click)="showDirection()">Show</button>
<button type="button" (click)="removeDirection()">Remove</button>
```

+ ts
```typescript
public show = true;

public showDirection() {
  this.show = true;
}

public removeDirection() {
  this.show = false;
}

```

#### DEMO GIF
![Imgur](https://i.imgur.com/hl99YVX.gif)
I hope it helps you~  😊

**Comment by aironpower** [comment]
Wow! Very simple. I'll try it. Thank you @explooosion

**Comment by mohanbkrishna** [comment]
Hi, nice solution, but if we have multiple directions(used ngFor in agm-direction element, then only latest one is removing, how can we implement for all

**Comment by mohanbkrishna** [comment]
??

**Comment by mohanbkrishna** [comment]
My code like this
<agm-map class="agm-map" [latitude]="lat" [longitude]="lng" >
            <span *ngFor="let mapDir of dir"  class="map-direction" >
              
              <agm-direction *ngIf="dir.length" [origin]="mapDir.origin" [destination]="mapDir.destination" [waypoints]="mapDir.waypoints" [visible]="mapDir.visible"  ></agm-direction>

           </span>
           </agm-map>

**Comment by explooosion** [comment]
Hi, this is a demo for using ngFor with `agm-direction`
I use `forEach` to set `visible = false`

+ HTML
```html
<div class="map">
  <agm-map [latitude]="lat" [longitude]="lng">
    <agm-direction *ngFor="let dir of dirArr" [origin]="dir.origin" [destination]="dir.destination" [visible]="dir.visible"></agm-direction>
  </agm-map>
  <button type="button" (click)="ShowDirection()">Show</button>
  <button type="button" (click)="HideDirection()">Hide</button>
</div>
```

+ TS
```ts
  public dirArr = [{
    origin: { lat: 24.799448, lng: 120.979021 },
    destination: { lat: 24.799524, lng: 120.975017 },
    visible: true,
  }, {
    origin: { lat: 24.799748, lng: 120.974021 },
    destination: { lat: 24.792524, lng: 120.975517 },
    visible: true,
  }];

  constructor() { }

  public HideDirection() {
    this.dirArr.forEach(dir => {
      dir.visible = false;
    });
  }

  public ShowDirection() {
    this.dirArr.forEach(dir => {
      dir.visible = true;
    });
  }
```

+ DEMO GIF
![map](https://user-images.githubusercontent.com/13682994/36378968-d134c67c-15b7-11e8-9658-ee29295b4cee.gif)

**Comment by mohanbkrishna** [comment]
Thanks for the quick response, actually I'm trying to remove individual routes, ie, there will be n number of routes(in dirArray) as check boxes, on selecting de-selecting particular check boxes, we need to render/remove particular routes, I'm able to do that in the above scenario(all render/remove), but if we rendered four routes and want to remove 1st and 3rd one, then not able to figured out in that scenario.

**Comment by explooosion** [comment]
You can add the object(id) to the array(dirArr) ,
and use ngModel to set the visible.

**Comment by explooosion** [comment]
the dirArray may like this:

+ TS
```ts
  public dirArr = [{
    id: 1,
    name: 'way1',
    origin: { lat: 24.799448, lng: 120.979021 },
    destination: { lat: 24.799524, lng: 120.975017 },
    visible: true,
  }, {
    id: 2,
    name: 'way2',
    origin: { lat: 24.799748, lng: 120.974021 },
    destination: { lat: 24.792524, lng: 120.975517 },
    visible: true,
  }];
```

and the check boxes:
```html
  <div *ngFor="let dir of dirArr">
    <input type="checkbox" [id]="dir.name" [(ngModel)]="dir.visible">
    <label [for]="dir.name">{{ dir.name }}</label>
  </div>
```

**Comment by explooosion** [comment]
By the way, you can set `preserveViewport: true` to keep the zoom constant at the number you set,
and focus at the first point.

It is part of `renderOptions` ( [DirectionsRendererOptions object specification](https://developers.google.com/maps/documentation/javascript/reference#DirectionsRendererOptions))

+ TS

```ts
  public dirArr = [{
    id: 1,
    name: 'way1',
    origin: { lat: 24.799448, lng: 120.979021 },
    destination: { lat: 24.799524, lng: 120.975017 },
    visible: true,
    renderOptions: {
      preserveViewport: true
    }
  }, {
    id: 2,
    name: 'way2',
    origin: { lat: 24.799748, lng: 120.974021 },
    destination: { lat: 24.792524, lng: 120.975517 },
    visible: true,
    renderOptions: {
      preserveViewport: true
    }
  }];
```

+ HTML

```html
<agm-direction *ngFor="let dir of dirArr" [origin]="dir.origin" [destination]="dir.destination" [visible]="dir.visible" [renderOptions]="dir.renderOptions"></agm-direction>
```

+ DEMO
![map](https://user-images.githubusercontent.com/13682994/36383144-3ac654a8-15c6-11e8-9e5d-77e2f92bfede.gif)

**Comment by mohanbkrishna** [comment]
Thank you so much @explooosion , your code helped me a lot. As a beginner I'm struggling a lot but your code is so simple to use.

**Comment by loredanKon** [comment]
My routes array has this format: 
`[{visible: true,
              start: {
                lat: item1.lat,
                lng: item1.lng
              },
              end: {
                lat: item2.lat,
                lng: item2.lng
              }}]`

I use `visible ` property to show/hide the route. In agm-direction I have also `onChange` event to get distance and time.

If I add routes to the array evrything works well but I have problems when I remove(hide) routes because `onChange` event doesn´t fire. 

Do you have another idea?
