### ISSUE TITLE
change marker infoWindow

### ISSUE THREAD

**Issue by AngelLuisSanchez** [explooosion/Agm-Direction#21]
Hi,

Is it possible to change marker InfoWindow ?

I want to change the text of popup...

![image](https://user-images.githubusercontent.com/9683844/39815594-c7f2c5cc-5398-11e8-95c9-cb6be7eec6e9.png)

And this is my code.

```
<agm-map #map [latitude]="oficina.latitud" [longitude]="oficina.longitud">
            <agm-direction [panel]="myPanel" [renderOptions]="options" [avoidHighways]='true' [provideRouteAlternatives]='true' [avoidTolls]='true' [optimizeWaypoints]='true' [waypoints]="ways"
                [origin]="origin" [destination]="dest" [travelMode]="travelMode"></agm-direction>
        </agm-map>
```

Thanks anyway!

**Comment by explooosion** [comment]
Sorry, it's only can change marker's label now. 😦

### Example

HTML
```html
<agm-direction ... [markerOptions]="markerOpts"></agm-direction>
```

TS

```ts
markerOpts = {
  origin: {
    label: 'origin marker',
  },
  destination: {
    label: 'destination marker',
  },
};
```

![image](https://user-images.githubusercontent.com/13682994/40625276-fc5ed2e2-62e3-11e8-8a19-b50f6eda3af8.png)  


This is a good issue, thank you.
I try to add features as soon as I can. 🙂

**Comment by AngelLuisSanchez** [comment]
Thanks!

I'll be waiting for you :)

**Comment by explooosion** [comment]
Hi! @AngelLuisSanchez 
Please install latest version ([^0.5.6](https://github.com/explooosion/Agm-Direction/releases/tag/0.5.6))

👉 [Doc](https://robby570.tw/Agm-Direction-Docs/source/featured/marker.html)

## Example

```html
<agm-direction ... [renderOptions]="renderOptions" [markerOptions]="markerOptions"></agm-direction>
```

```typescript
public renderOptions = {
    suppressMarkers: true,
}

public markerOptions = {
    origin: {
        icon: 'https://i.imgur.com/7teZKif.png',
    },
    destination: {
        icon: 'https://i.imgur.com/7teZKif.png',
        infoWindow: `
        <h4>Hello<h4>
        <a href='http://www-e.ntust.edu.tw/home.php' target='_blank'>Taiwan Tech</a>
        `
    },
}
```

![img](https://i.imgur.com/FLCk1Ix.png)
