### ISSUE TITLE
How to save way points

### ISSUE THREAD

**Issue by henoktsegaye** [explooosion/Agm-Direction#22]
by the way i want to say that is a really good thing you done out there , i was wondering how to save a way points after some body drags the direction  cause we don't want to start fresh next time , we wanted to show the way points he /she dragged

**Comment by explooosion** [comment]
Hi @henoktsegaye !

When he/she drags the direction, you can get the information from `(onChange)` event.
The event's payload likes the following picture:

## Payload
![image](https://user-images.githubusercontent.com/13682994/40624452-58194c20-62df-11e8-9cb2-1911078c8704.png)

#### **request** 
The new event's payload, so you can save these `waypoints`.

## Example:

HTML

```html
<agm-map>
<agm-direction ... [waypoints]="waypoints" (onChange)="dirChange($event)"></agm-direction>
</agm-map>
```

TS

```ts
waypoints: any = [];
dirChange(event: any) {
    console.log(event);
    this.waypoints = event.request.waypoints;
}
```
