### ISSUE TITLE
How to recieve log data from the library 

### ISSUE THREAD

**Issue by ClumsyPenguin** [explooosion/Agm-Direction#23]
i used your library with success, i want the console.log the calls you make to agm / google maps to view more information of the direction in a sideview windows 

is this possible with your library / directive

**Comment by explooosion** [comment]
Hi @ClumsyPenguin !

`@Output` events only `onChange` . 😦
When you create or drag direction, you can get the information from this event.

HTML
```html
<agm-map>
  <agm-direction ... (onChange)="dirChange($event)"></agm-direction>
</agm-map>
```

TS

```ts
dirChange(event: any) {
    console.log(event);
}
```
