### ISSUE TITLE
support for placeid/name

### ISSUE THREAD

**Issue by InsOpDe** [explooosion/Agm-Direction#25]
As the [docs](https://developers.google.com/maps/documentation/javascript/directions?hl=en#DirectionsRequests) state origin and destination can be of type
`origin: LatLng | String | google.maps.Place,`
so I wondered whether you are supporting a location string or a placeId

**Comment by explooosion** [comment]
Hi @InsOpDe 
The Agm-Direction only support `origin: LatLng | String` now,
It's a good idea to use `placeId`

**Comment by explooosion** [comment]
Hi @InsOpDe  

You can input a location string or a placeId.

#### Example

```html
<agm-direction ... [origin]="dir.origin" [destination]="dir.destination"</agm-direction>
```

```typescript
this.dir = {
  origin: 'Taipei Main Station',
  destination: 'Taipei Bus Station',
}
```
