### ISSUE TITLE
No provider for GoogleMapsAPIWrapper

### ISSUE THREAD

**Issue by ahmedwerpx** [explooosion/Agm-Direction#29]
when i installed npm install agm-direction@0.3.7 
This error appeared 
if i import "GoogleMapsAPIWrapper" and add it in provider i get the same error
if i install agm-direction < 0.3.7 
this error goes and get a new error "Metadata version mismatch for module node_modules/agm-direction/agm-direction.d.ts, found version 4, expected 3"

**Comment by explooosion** [comment]
What is your Angular version? 😦
Is it possible to use the latest version angular in your project?

I recommend that you install the latest version - agm-direction@0.5.9

**Comment by explooosion** [comment]
Please let me know if you have any questions. 🙂
