### ISSUE TITLE
Displaying the list of Directions

### ISSUE THREAD

**Issue by LancerOfTruth** [explooosion/Agm-Direction#3]
Is there any way to display the list of **turn by turn directions**?  

In the pure javascript solution, you would use the code below, but I don't see any way of doing that using this npm package.

`directionsDisplay.setPanel(document.getElementById('directions-panel'));`

**Comment by explooosion** [comment]
Hi! I have upgraded an package.
You can display the list of turn by turn directions.
+  [Displaying text directions with setPanel()](https://developers.google.com/maps/documentation/javascript/examples/directions-panel?hl=zh-tw)  

#### Version 0.3.2 : 
+ attribute: panel
  
#### Add Panel Example:
+ html 
```html
<div class="map">
    <agm-map [latitude]="lat" [longitude]="lng">
        <agm-direction *ngIf="dir" [origin]="dir.origin" [destination]="dir.destination" [panel]="myPanel"></agm-direction>
    </agm-map>
    <button type="button" (click)="getDirection_A()">Direction_A</button>
    <button type="button" (click)="getDirection_B()">Direction_B</button>
</div>
<div #myPanel></div>
```

+ css
```css
.map {
    float: left;
    margin-right: 20px;
    width: 50vw;
}
.map agm-map {
    height: 400px;
}
.panel {
    float: left;
    width: 40vw;
}
```

+ ts
```typescript
  lat: Number = 24.799448;
  lng: Number = 120.979021;
  zoom: Number = 14;

  dir = undefined;

  constructor() {  }

  public getDirection_A() {
    this.dir = {
      origin: { lat: 24.799448, lng: 120.979021 },
      destination: { lat: 24.799524, lng: 120.975017 }
    }
  }

  public getDirection_B() {
    this.dir = {
      origin: { lat: 24.799748, lng: 120.974021 },
      destination: { lat: 24.792524, lng: 120.975517 }
    }
  }
```

+ Or you can use function:
```html
 <agm-direction ...  [panel]="setPanel()"></agm-direction>
```

```html
<div id="myPanel"></div>
```

```typescript
  public setPanel() {
    return document.querySelector('#myPanel');
  }
```


#### DEMO GIF
![Imgur](https://i.imgur.com/i2HJLFB.gif)
  
I hope it helps you~  😃

**Comment by LancerOfTruth** [comment]
This is great! But I'm getting a typescript error when  trying to compile the code using webpack:

>     ERROR in [at-loader] ./node_modules/agm-direction/src/agm-directions.directive.ts:16:3
>         TS2322: Type 'undefined' is not assignable to type 'object'.

I believe it may be here:

`  @Input() panel: object = undefined;`

**Comment by explooosion** [comment]
You're right. I have received your PR

Thank you! 😃

**Comment by Brenton30** [comment]
Awesome stuff so far, I was just wondering if it is possible at all to also enter a start time for the travel. This is because for some of my directions I am using the transit mode and if you do not provide a travel time then google will just return any timings for the public transport. e.g. If I set off at 8am and have a 47m transit I'd want to see those timings in the directions list? Currently it would show timings for a bus from 11am etc.

**Comment by explooosion** [comment]
Hi ! @Brenton30 

Hi! I have upgraded an package,
please install the latest version `0.4.1`.

### Example:

+ HTML
```html
 <agm-direction ... [transitOptions]="transitOptions" [travelMode]="travelMode"></agm-direction>
```

+ TS
```ts
 transitOptions = {
      departureTime: new Date('2018/03/20 12:00'),
      modes: ['BUS'],
 };
 travelMode = 'TRANSIT';
```

### Reference
+ [Directions Service](https://developers.google.com/maps/documentation/javascript/directions?hl=en-US) - [TransitOptions](https://developers.google.com/maps/documentation/javascript/directions?hl=en-US#TransitOptions)

### Demo
![image](https://user-images.githubusercontent.com/13682994/37621940-615fc90a-2bfb-11e8-8145-963e061ff83b.png)


Thank you for your advice. 😄

**Comment by Brenton30** [comment]
Hi, seems to all be working fine!
However, do you have any idea on how to pass in a time and ignore a time zone. This is becuase I'm using the travel time for different countries. e.g. If I pass in 8am for the Uk it works fine but dosen't seem to work for other countries in different time zones?

**Comment by Brenton30** [comment]
Code:
![dsdsd](https://user-images.githubusercontent.com/28558058/38882053-2df77f5a-4261-11e8-94a3-1fc05edc5aaa.PNG)
![vfvvccv](https://user-images.githubusercontent.com/28558058/38882057-2f90a422-4261-11e8-92cc-d45fb985995d.PNG)
Value passed in:
![fdd](https://user-images.githubusercontent.com/28558058/38882161-67843678-4261-11e8-918f-ca65bf7a710c.PNG)
Result:
![fdfdsfsd](https://user-images.githubusercontent.com/28558058/38882062-319137d2-4261-11e8-8cf8-2d58f536fe8e.PNG)

@explooosion Why is this incorrect? It keeps giving me times for transits for the current time, not the one passed in?
