### ISSUE TITLE
build with --prod type r error

### ISSUE THREAD

**Issue by amyogiji** [explooosion/Agm-Direction#31]
I'm using Angular 6 .
every thing works fine with _ng serve_ & _ng build_ but with _ng build --prod_ the map doesn't open and has this type r is not a constructor in console.

**Comment by pedro412** [comment]
same here
---------------
![image](https://user-images.githubusercontent.com/24465570/42245437-702d61f0-7ede-11e8-9ed1-9416f22b8546.png)



thx.

**Comment by amyogiji** [comment]
anyone has solution or any alternative for this

**Comment by pedro412** [comment]
not yet - 💃

**Comment by amyogiji** [comment]
thanks for the reply please look

**Comment by explooosion** [comment]
Please install the latest version `0.6.0` now. 🙂
You can check out the latest [release](https://github.com/explooosion/Agm-Direction/releases/tag/0.6.0) info.

**Comment by amyogiji** [comment]
still the same error `ERROR TypeError: r is not a constructor` with `ng build --prod`

**Comment by explooosion** [comment]
Hi, @amyogiji 
This is an example build with angular-cli, and it's works fine.
Maybe you can check it out to compare with your project.

Google drive - [agm-example](https://drive.google.com/open?id=1G5UBfdhGNUlG7hpHGivUOXGD1VD8qXdM)

**Comment by explooosion** [comment]
This is an angular-cli version:

![image](https://user-images.githubusercontent.com/13682994/42564899-94a9701c-8534-11e8-8972-934c3753f44a.png)

**Comment by pedro412** [comment]
`{
    "name": "newproject",
    "version": "1.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@agm/core": "^1.0.0-beta.3",
        "@angular/animations": "^6.0.7",
        "@angular/cdk": "^6.1.0",
        "@angular/common": "^6.0.7",
        "@angular/compiler": "^6.0.7",
        "@angular/core": "^6.0.7",
        "@angular/forms": "^6.0.7",
        "@angular/http": "^6.0.7",
        "@angular/material": "^6.1.0",
        "@angular/platform-browser": "^6.0.7",
        "@angular/platform-browser-dynamic": "^6.0.7",
        "@angular/router": "^6.0.7",
        "@fortawesome/angular-fontawesome": "0.1.0-10",
        "@fortawesome/fontawesome": "^1.1.8",
        "@fortawesome/fontawesome-free-brands": "^5.0.13",
        "@fortawesome/fontawesome-free-regular": "^5.0.13",
        "@fortawesome/fontawesome-free-solid": "^5.0.13",
        "@fortawesome/fontawesome-svg-core": "^1.2.0-14",
        "@fortawesome/free-solid-svg-icons": "^5.1.0-11",
        "@ng-bootstrap/ng-bootstrap": "^2.1.0",
        "agm-direction": "^0.6.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.5.4",
        "ng-lazyload-image": "^4.0.0",
        "ng-recaptcha": "^3.0.5",
        "ng2-search-filter": "^0.4.7",
        "ngx-loading": "^1.0.14",
        "ngx-pagination": "^3.1.1",
        "rxjs": "^6.0.0",
        "rxjs-compat": "^6.2.0",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.8",
        "@angular/cli": "6.0.8",
        "@angular/compiler-cli": "^6.0.7",
        "@angular/language-service": "^6.0.7",
        "@types/googlemaps": "^3.30.10",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~1.4.2",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.7.2"
    }
}
`

**Comment by amyogiji** [comment]
is it working for you ?

**Comment by pedro412** [comment]
Maybe this have something to do with this issue:

https://github.com/angular/angular-cli/issues/9929

**Comment by explooosion** [comment]
The latest version is 7.0.1 now, and `ng build --prod` in Angular 6 works fine.
Are there still problems?

**Comment by explooosion** [comment]
Please let me know if you have any questions.

**Comment by pedro412** [comment]
Hi Robby, just to let you know, indeed now everything is working fine, thank you very much for your support.
