### ISSUE TITLE
property visibility not checking value unless changes

### ISSUE THREAD

**Issue by Drea1989** [explooosion/Agm-Direction#34]
Hello, 
I am using: 
"agm-direction": "^0.6.0"
"@agm/core": "^1.0.0-beta.3"
"@angular/core": "^6.1.0"

I have noticed that if you set the value of visibility to false it won't be considered unless you change it to true before.

example:
this won't actually hide the direction:
` <agm-direction [visible]="false">`
this won't as well:
```
show = false;
<agm-direction [visible]="show">
```
cheers

**Comment by explooosion** [comment]
Please install the latest version. 🙂

latest: 0.7.1

```bash
npm install agm-direction@lastest
```

**Comment by explooosion** [comment]
Please let me know if you have any questions. 🙂
