### ISSUE TITLE
Getting Over_Query_Limit

### ISSUE THREAD

**Issue by bncunha** [explooosion/Agm-Direction#35]
Hello explooosion,

I know that Google Maps API have query limits, and I have to show more directions then than limits allow.
Google Maps API limit says that they have a limit of 50 requests per second.

So I'm pushing an array 10 in 10 directions and waiting 3 seconds... then I'm pushing more 10, until the last element. But I'm still getting the error, and I'm out of limits.

There is some solution for this?

**Comment by explooosion** [comment]
Hi, check out #72
