### ISSUE TITLE
Change Color of the direction

### ISSUE THREAD

**Issue by er-shrey** [explooosion/Agm-Direction#37]
How can we change the color of the direction line

**Comment by explooosion** [comment]
Hi! @er-shrey

You can use [renderOptions](https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRendererOptions) to set the color of the direction line.

### Example:

```html
<agm-direction ... [renderOptions]="renderOptions"></agm-direction>
```

```typescript
renderOptions = {
  polylineOptions: {
    strokeColor: "#f00" // or "red" 
  }
}
```
 
[Live Demo](https://stackblitz.com/edit/angular-5rxhbf)

**Comment by er-shrey** [comment]
Where can I get all the possible render options?

**Comment by explooosion** [comment]
### DirectionsRendererOptions interface

[https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRendererOptions](https://developers.google.com/maps/documentation/javascript/reference/directions#DirectionsRendererOptions)

**Comment by er-shrey** [comment]
thanks a lot
