### ISSUE TITLE
Distance and other values

### ISSUE THREAD

**Issue by er-shrey** [explooosion/Agm-Direction#38]
From the API response, we get:
routes>>legs>>distance

I want the distance that I got from the API response. How can I access it with AGM-Direction?

**Comment by er-shrey** [comment]
Thanks, Got it

**Comment by er-shrey** [comment]
Sometimes the API will result as:

geocoded_waypoints:[{}, {}]
    0:{}
    1:{}
routes:[]
status:"ZERO_RESULTS"


i.e. directions not found, at this time (onChange) event will not get fired. Is there any workaround.

(let the user gave wrong destination location, say in the mid of ocean)

**Comment by explooosion** [comment]
Hey I think it's a good question, could you re-send your new question in another new page ? We could discussion on that page.
