### ISSUE TITLE
Get the API response directly as soon as it runs successfully

### ISSUE THREAD

**Issue by er-shrey** [explooosion/Agm-Direction#41]
Sometimes the API will result as:

geocoded_waypoints:[{}, {}]
0:{}
1:{}
routes:[]
status:"ZERO_RESULTS"

i.e. directions not found, at this time (onChange) event will not get fired. Is there any workaround.

(let the user gave wrong destination location, say in the mid of ocean)

**Comment by explooosion** [comment]
Hi! @er-shrey  .

Please install the latest version(0.7.2).

HTML

```html
  <agm-direction
	...
    (onResponse)="onResponse($event)"
  >
  </agm-direction>
```

TypeScript

```typescript
  public onResponse(event: any) {
    console.log('onResponse', event);
  }
```

**Comment by er-shrey** [comment]
Thanks buddy
