### ISSUE TITLE
Export directive type reference

### ISSUE THREAD

**Issue by DavideCanton** [explooosion/Agm-Direction#44]
Actually, I can't get a reference to the directive, cause the type is not exported and the directive has no exportAs attribute set.

It's by design or it's a bug?

I think it should be allowed, in order to do view queries and interact with the directive from a component.

**Comment by explooosion** [comment]
Hi @DavideCanton !

Thanks for your reply.
Agm-direction was generated by [angular-library-starter](https://github.com/robisim74/angular-library-starter).

Maybe this problem is closely relate to angular-library-starter.😦
