### ISSUE TITLE
Error with AOT compilation

### ISSUE THREAD

**Issue by henriquefischer** [explooosion/Agm-Direction#45]
I step into this problem trying to use the agm-direction, and this SO link solved for me, but is not allowing to use the AOT.

https://stackoverflow.com/questions/51135048/agm-direction-build-type-r-error

**Comment by explooosion** [comment]
Hi @henriquefischer !
What is your agm-direction version, please install the latest version.

I have create the new project, and work fine.

The following commands are successful.
- ng serve --aot
- ng serve --prod --aot
- ng build --aot
- ng build --prod --aot 

## Commands

![image](https://user-images.githubusercontent.com/13682994/46241505-87ee3180-c3ed-11e8-8aa2-757c51111457.png)

![image](https://user-images.githubusercontent.com/13682994/46241508-90df0300-c3ed-11e8-846a-c6197aade5f3.png)

![image](https://user-images.githubusercontent.com/13682994/46241530-bff57480-c3ed-11e8-92dc-e6156379f6e1.png)

![image](https://user-images.githubusercontent.com/13682994/46241534-e0253380-c3ed-11e8-83d8-11fba9b19430.png)


## Angular-Cli

- latest version.

![image](https://user-images.githubusercontent.com/13682994/46241544-034fe300-c3ee-11e8-8d4b-41697f67310d.png)

**Comment by explooosion** [comment]
If there is any question, please let me know. :)
