### ISSUE TITLE
Set the bounds and Zoom level 

### ISSUE THREAD

**Issue by tvbishan** [explooosion/Agm-Direction#48]
I have one marker in one country and other in some other country.  I want to set the zoom level exactly covering all the markers on the map.

How can I achieve this?

**Comment by P1X3** [comment]
According to google maps api page the map viewport is changed automatically to display the route fully. There is an option to set preserveViewport property of DirectionsRendererOptions to false which would prevent viewport changes. But again, by default it should zoom to show full directions/route.

**Comment by explooosion** [comment]
Thanks for response. 🙂
