### ISSUE TITLE
duplicate icon when customize

### ISSUE THREAD

**Issue by manunoly** [explooosion/Agm-Direction#50]
Hello thanks for your hard work, the icon is duplicate when you use markerOptions

![directionduplicateicon](https://user-images.githubusercontent.com/636156/46820106-f9fa3b00-cd4a-11e8-9f1a-c013ce23353b.png)

![directionduplicateicon](https://user-images.githubusercontent.com/636156/46820378-aa683f00-cd4b-11e8-995d-a82c2b51b0b7.png)

**Comment by explooosion** [comment]
Hi @manunoly !

You need to set `renderOptions` if you use custom icons.
For more information, please ceheck out the [Document](https://robby570.tw/Agm-Direction-Docs/source/featured/marker.html).

## Example

TS

```html
<agm-direction 
    ... 
    [renderOptions]="renderOptions" 
    [markerOptions]="markerOptions"
>
</agm-direction>
```

HTML

```typescript
public renderOptions = {
    suppressMarkers: true,
}

public markerOptions = {
    origin: {
        icon: 'https://www.shareicon.net/data/32x32/2016/04/28/756617_face_512x512.png',
        draggable: true,
    },
    destination: {
        icon: 'https://www.shareicon.net/data/32x32/2016/04/28/756626_face_512x512.png',
        label: 'MARKER LABEL',
        opacity: 0.8,
    },
}
```

**Comment by manunoly** [comment]
thanks man, you are incredible fast!!  
close the issue
