### ISSUE TITLE
Injection token error when using @agm/core > 1.0.0-beta.3

### ISSUE THREAD

**Issue by vvandens** [explooosion/Agm-Direction#51]
We have just tried to migrate our project on @agm/core 1.0.0-beta.5 and AgmDirection fails now to resolve GoogleMapsAPIWrapper injection token. It seems that @agm/core >1.0.0-beta.3 does not provide GoogleMapsAPIWrapper injection token anymore. 

Error: StaticInjectorError(AppModule)[AgmDirection -> GoogleMapsAPIWrapper]: 
  StaticInjectorError(Platform: core)[AgmDirection -> GoogleMapsAPIWrapper]: 
    NullInjectorError: No provider for GoogleMapsAPIWrapper!

BTW, thanks for the great work !

**Comment by vvandens** [comment]
After a day of investigation, the problem comes from the node_modules being packaged in the NPM Agm-Direction module. Everything runs smoothly when deleting the node_module/agm-direction/node_module directory from the project. I believe it should not be pushed to NPM...

**Comment by vvandens** [comment]
This seems to finally be a problem with *yarn install* hoisting the Agm-Direction dependencies in a nested node_modules. *npm install* does not show this issue. So I don't think it has anything to do with Agm-Direction packaging...
Sorry for the noise.

**Comment by explooosion** [comment]
Hi @vvandens !
Sorry for the late reply. I appreciate it.
I'll check it out, and update the dependency.
