### ISSUE TITLE
Static Injection Error Nothing Works

### ISSUE THREAD

**Issue by micahosborne** [explooosion/Agm-Direction#54]
core.js:12584 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[AgmDirection -> GoogleMapsAPIWrapper]: 
  StaticInjectorError(Platform: core)[AgmDirection -> GoogleMapsAPIWrapper]: 
    NullInjectorError: No provider for GoogleMapsAPIWrapper!
Error: StaticInjectorError(AppModule)[AgmDirection -> GoogleMapsAPIWrapper]

**Comment by explooosion** [comment]
Hi, @micahosborne .

Could you Please provide me the details about your project version?

- angular
- agm
- agm-direction
- node

**Comment by explooosion** [comment]
Hi @harleenarora !

Please install the latest version of `@agm/core`.

```sh
npm install @agm/core
```

or

```sh
yarn add @agm/core
```

**Comment by explooosion** [comment]
#55

**Comment by explooosion** [comment]
Hi @wilfriednhw !

If you remove `agm-direction`, the map with `agm` still working?

**Comment by vikingschris** [comment]
agm/core: "1.0.0-beta.3",
agm-direction: "0.7.4"
node: "v8.12.0"

i'm getting the same error: "StaticInjectorError(AppModule) [AgmDirection -> GoogleMapsAPIWrapper]: StaticInjectorError (Platform core) [AgmDirection -> GoogleMapsAPIWrapper]: NullInjector: No provider for GoogleMapsAPIWrapper". i removed the agm-direction and agm is working. what could be the issue?

**Comment by vikingschris** [comment]
i was able to resolve my error by moving a service that uses the mapsAPIloader from shared module to directly into the component.

**Comment by wilfriednhw** [comment]
@explooosion 
Yes when i remove agm-direction in component.html, the map appears.

**Comment by wilfriednhw** [comment]
?

**Comment by vikingschris** [comment]
@explooosion is there a solution for this?

**Comment by thangaprakashari** [comment]
same issue any suggestion

**Comment by explooosion** [comment]
Hi @micahosborne @wilfriednhw  @vikingschris @thangaprakashari !
I had find the problem.

[https://github.com/explooosion/Agm-Direction/blob/master/package.json](https://github.com/explooosion/Agm-Direction/blob/master/package.json)

```json
"dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "tslib": "^1.9.0"
  },
"peerDependencies": {
    "@angular/common": ">= 7.0.0",
    "@angular/core": ">= 7.0.0"
},
```

- Angular5 should install agm/core of beta.3
- Angular6~7 should install agm/core of beta.5


@agm/core witch in `Dependencies`, should move to `peerDependencies`,
otherwise, agm-direction will install the latest dependency of agm/core(beta.5).

That's a reason why agm-direction will crash in Angular5.

I'll try to fix it, thank you for reporting this.

**Comment by wilfriednhw** [comment]
hi @explooosion, 
OK i got it,
thank you.

**Comment by explooosion** [comment]
Hi!

Please install the latest version:

## Steps to Fix

Remove

```sh
npm uninstall agm-direction # yarn remove agm-direction
```

Install

```sh
npm install agm-direction -S # yarn add agm-direction
```

## Checkout the agm/core version

#57 

In Angular2~5:
```sh
@agm/core": "1.0.0-beta.3
```

In Angular6~7:
```sh
@agm/core": "1.0.0-beta.5
```

**Comment by wilfriednhw** [comment]
HI @explooosion  
thank you for your answer, I tried what you said, this previouly error is solved but direction still does not display, and in the console I have this error: <b> directions Service: This API project is not authorized to use this API. JavaScript API services please see: </ b>

**Comment by explooosion** [comment]
Hi @wilfriednhw

Can you take a screenshot ?
Or provide the source code.
I'm not sure what is your error message.

**Comment by explooosion** [comment]
Maybe your key is not valid.

You can take a look the following links.
- [This API project is not authorized to use this API. Please ensure that this API is activated in the APIs Console](https://stackoverflow.com/questions/32994634/this-api-project-is-not-authorized-to-use-this-api-please-ensure-that-this-api/32998566)
- [[Resolved] Google API REQUEST_DENIED – This API project is not authorized to use this API.](https://toolset.com/forums/topic/google-api-request_denied-this-api-project-is-not-authorized-to-use-this-api/)

**Comment by wilfriednhw** [comment]
Hi @explooosion ,
thank you for your answer, i have missed to activate "direction api" in console google where i genereted api key for google map.
Now it is work fine, 
THANK FOR YOUR HELP YOU ARE AMAZING.

**Comment by explooosion** [comment]
My pleasure. 🙂
