### ISSUE TITLE
How can i redraw direction? 

### ISSUE THREAD

**Issue by cdevent** [explooosion/Agm-Direction#56]
Hi!
When i'm pushing waypoint object to waypoints  array, my direction not re-drawing. 
I can't find any documentation how to update direction when waypoint added

Trying to add like this to waypoints array: 

`<input id="waypoint" type="text"  class="form-control"  name="waypoint" ngx-google-places-autocomplete [options]='autoCompleteOptions' #placesRef="ngx-places" (onAddressChange)="addWaypoints($event)"/>`

```
  addWaypoints(waypoint){
    this.waypoints.push( 
      { 
        location: { 
          lat: waypoint.geometry.location.lat(), 
          lng: waypoint.geometry.location.lng() 
          },
        stopover: true
      }
    );
  }
```

**Comment by explooosion** [comment]
Hi @cdevent !

You can checkout #14

**Comment by cdevent** [comment]
Yeap! many thanks! All works perfect!
