### ISSUE TITLE
add path of html view as value of infowindow parameter

### ISSUE THREAD

**Issue by wilfriednhw** [explooosion/Agm-Direction#58]
Hi @explooosion,
iis it possible to add path of html view as value  of infowindow parameter?
_here is an exemple:_

**INSTEAD OF :**
destination: {
        icon: 'https://i.imgur.com/7teZKif.png',
        infoWindow: `
        <h4>Hello<h4>
        <a href='http://www-e.ntust.edu.tw/home.php' target='_blank'>Taiwan Tech</a>
        `
    },

**WE HAVE :**

destination: {
        icon: 'https://i.imgur.com/7teZKif.png',
        infoWindow: 'src/app/layout/dashboard/infowindow.html'
    },

**Comment by explooosion** [comment]
Hi @wilfriednhw .

You can use iframe.

### Example

```ts
public markerOptions = {
  origin: {
    icon: 'https://i.imgur.com/7teZKif.png',
    infoWindow: '<h2>Origin</h2>',
  },
  destination: {
    icon: 'https://i.imgur.com/7teZKif.png',
    infoWindow: `
    <iframe
      src='/info'
      width='400'
      height='200'
      frameborder='0'
    >
    <iframe>`,
  },
};
```

[app-routing.module.ts]

```ts
const routes: Routes = [
  { path: '', component: MyMapComponent },
  { path: 'info', component: InfoWindowComponent },
];
```
