### ISSUE TITLE
How to change the marker at source and destination

### ISSUE THREAD

**Issue by explooosion** [explooosion/Agm-Direction#6]

**Comment by nishant0131** [comment]
Hi thanks for reply. but I'm still facing this error.
![image](https://user-images.githubusercontent.com/23257562/36099444-b35623ce-1028-11e8-8419-ca113eeed0ae.png)

**Comment by explooosion** [comment]
Hi what is your package version?

Try to install the latest version `0.3.5`

**Comment by nishant0131** [comment]
Wow.... It works, thanks Robby.

One more thing, I want to use different icon for source and destination. Is it possible?

**Comment by explooosion** [comment]
This will be a little bit difficult... 🤔

It will require new methods in this package
I will give it a try.

Or following the steps: 
+  [Custom Directions Panel with Google Maps API v3](https://thewebstorebyg.wordpress.com/tag/custom-direction-markers/)

**Comment by explooosion** [comment]
Hey! @nishant0131 👋🏽
you can try this way

1. Remove direction's markers
2. Use [AgmMarker](https://angular-maps.com/api-docs/agm-core/directives/AgmMarker.html) to add origin and destination markers

#### ⚡️ Remove direction's markers
+ TS
```ts
  options = {
    suppressMarkers: true,
  };
```

+ HTML
```html
  <agm-direction ... [renderOptions]="options"></agm-direction>
```

#### ⚡️ Add markers

+ TS
```ts
  orinIcon = 'http://image.ibb.co/bZ3wLn/origin.png';
  desIcon = 'https://image.ibb.co/cLwp5n/678111_map_marker_256.png';
```

+ HTML
```html
<agm-marker *ngIf="dir" [latitude]="dir.origin.lat" [longitude]="dir.origin.lng" [iconUrl]="orinIcon"></agm-marker>
<agm-marker *ngIf="dir" [latitude]="dir.destination.lat" [longitude]="dir.destination.lng" [iconUrl]="desIcon"></agm-marker>
```

#### ⚡️ Result
![image](https://user-images.githubusercontent.com/13682994/36141694-b23ceab4-10e0-11e8-92bb-850b25c99c8b.png)

I hope it helps you~ 😃

**Comment by nishant0131** [comment]
Thanks Robby. 
I have already implemented this approach and it also work fine. But I will be pretty awesome if we can implement it on agm-direction.

**Comment by explooosion** [comment]
Yep... It must be a problem.  😧
 
Sometimes, what you said also happen to me. My marker also points to the actual buildings instead of the roads when I using AgmMarker. 
  
Actually, how to make it work is setting the markers and the directions on the same layer and the marker's position will point by callback(response).
  
##### For example:
+ [Custom Directions Panel with Google Maps API v3](https://thewebstorebyg.wordpress.com/tag/custom-direction-markers/)
```ts
directionsRender = function(source, destination) {
	var request = {
		origin: source,
		destination: destination,
		provideRouteAlternatives: false, 
		travelMode: google.maps.DirectionsTravelMode.DRIVING
	};		

	directionsService.route(request, function(response, status) {
		if (status == google.maps.DirectionsStatus.OK) {
			directionsDisplay.setDirections(response);
			var _route = response.routes[0].legs[0]; 
			pinA = new google.maps.Marker({
				position: _route.start_location,
				map: map,
				icon: markerA
			}),
			pinB = new google.maps.Marker({
				position: _route.end_location,
				map: map,
				icon: markerB
			});
		}
	});
}, // directionsRender Ends
```

**Comment by nishant0131** [comment]
ok thanks @explooosion.

**Comment by explooosion** [comment]
#15
