### ISSUE TITLE
How to use this for aircraft? From Origin to current position Airplane mode.

### ISSUE THREAD

**Issue by joaquintoral** [explooosion/Agm-Direction#60]

**Comment by explooosion** [comment]
Sorry, I didn't find Airplane mode.

I’m not sure I get your meaning.  

Ref
- [directions#TravelMode](https://developers.google.com/maps/documentation/javascript/reference/directions#TravelMode)
- [How to set travel mode to “Flight” in google map direction API .
](https://stackoverflow.com/questions/35502261/how-to-set-travel-mode-to-flight-in-google-map-direction-api)
