### ISSUE TITLE
Show route using existing encoded polyline on agm-map

### ISSUE THREAD

**Issue by JaguarXF** [explooosion/Agm-Direction#74]
I am using agm-map to show vehicle routes. I have an existing polyline which I store in the DB when the path is first created. I would like to reuse this existing polyline from the DB to draw the route on the map using agm-direction. I want to use the historic polyline which i store so that I can have access to the exact route that was used first time. How can I go about using an existing polyline with agm-direction or is there another way I should be using this?

**Comment by explooosion** [comment]
You can use [@agm/core](https://angular-maps.com/api-docs/agm-core/index.html) - [AgmPolyline](https://angular-maps.com/api-docs/agm-core/directives/agmpolyline)

```html
<agm-polyline-point [latitude]="latA" [longitude]="lngA">
</agm-polyline-point>
```

Or you can pass the waypoints to the direction with agm-direction.

Maybe issue from #24 is help for you.
