### ISSUE TITLE
Outputs directive don't work

### ISSUE THREAD

**Issue by devpato** [explooosion/Agm-Direction#75]
https://robby570.tw/Agm-Direction/directives/AgmDirection.html#destinationDrag

I'm trying to use the Output directive when the marker has moved to retrive the lat and long but the function is not even getting called when I move the marker

https://stackblitz.com/edit/agm-direction-demo-mzbaq3?file=app/app.component.ts

```
<agm-map [latitude]="lat" [longitude]="lng">
<agm-direction 
    [origin]="origin"
    [destination]="destination"
    [renderOptions]="renderOptions" 
    [markerOptions]="markerOptions"
    (onChange)="getcoords($event)"
>
</agm-direction>
</agm-map>
```

```
public markerOptions = {
    origin: {
        draggable: true,
    },
    destination: {
        draggable: true,
    },
}

  lat: Number = 24.799448
  lng: Number = 120.979021

  origin = { lat: 24.799448, lng: 120.979021 }
  destination = { lat: 24.799524, lng: 120.975017 }

  getcoords($event) {
    console.log($event.request.destination.location.lat());
    console.log($event.request.destination.location.lng())
  }
```

**Comment by explooosion** [comment]
Hi @devpato !


The following are examples for detecting marker dragged event.


### STEP 1 - Create Draggable Marker

If you use default marker icon, please set up `renderOptions`.

HTML

```html
  <agm-direction
      ...
      [renderOptions]="renderOptions"
  >
  </agm-direction>
```

TS

```typescript
 public renderOptions = {
    draggable: true,
  };
```

If you use custom marker, please set up `renderOptions` and `markerOptions`.

HTML

```html
  <agm-direction
      ...
      [renderOptions]="renderOptions"
      [markerOptions]="markerOptions"
  >
```

TS

```typescript
  public renderOptions = {
    suppressMarkers: true,
  };

  public markerOptions = {
    origin: {
      icon: 'https://www.shareicon.net/data/32x32/2016/04/28/756617_face_512x512.png',
      draggable: true,
    },
    destination: {
      icon: 'https://www.shareicon.net/data/32x32/2016/04/28/756626_face_512x512.png',
      draggable: true,
    },
  };
```

### STEP 2 - Add Change Listener

Getting location from `request.destination.location.lat()` perhaps not a best way.
According to the document ([Directions Routes](https://developers.google.com/maps/documentation/javascript/directions#Routes)), you can get the location from legs in result.

Here is an official example  - [DraggableDirections](https://developers.google.com/maps/documentation/javascript/directions#DraggableDirections)

The following example is my way, please check out.

```html
  <agm-direction
      ...
      (onChange)="getcoords($event)"
  >
  </agm-direction>
```

```typescript
  getcoords($event) {
    const { end_location, start_location } = $event.routes[0].legs[0];
    console.log(start_location.lat(), start_location.lng());
    console.log(end_location.lat(), end_location.lng());
  }
```

![image](https://user-images.githubusercontent.com/13682994/67636018-fcecad00-f906-11e9-9a00-56235ab742f3.png)

ref - [https://robby570.tw/Agm-Direction-Docs/source/properties/input.html](https://robby570.tw/Agm-Direction-Docs/source/properties/input.html)
