### ISSUE TITLE
Add markerClickable boolean option for Origin and Destination markers

### ISSUE THREAD

**Issue by Kernolsie** [explooosion/Agm-Direction#77]
I would like to be able to disable the clickable property of the markers. My suggestion would be something like this in you master code in the AgmDirection.prototype.setMarker  function:

```
if (markerOpts.markerClickable != null && markerOpts.markerClickable == true) {
                marker.addListener('click', function () {
                    /** @type {?} */
                    var infowindoContent = typeof markerOpts.infoWindow === 'undefined' ? content : markerOpts.infoWindow;
                    _this.infoWindow.setContent(infowindoContent);
                    _this.infoWindow.open(map, marker);
                });
            }
```

**Comment by explooosion** [comment]
Hi @Kernolsie !

I found that google map [MarkerOptions interface](https://developers.google.com/maps/documentation/javascript/reference/marker?hl=zh-tw#MarkerOptions) already have [clickable](https://developers.google.com/maps/documentation/javascript/reference/marker?hl=zh-tw#MarkerOptions.clickable) property.

It's a bug when clickable is false but click listener still working.

Thanks for the suggestion. 🙂
