### ISSUE TITLE
Switching waypoints dynamically

### ISSUE THREAD

**Issue by Joni-89** [explooosion/Agm-Direction#79]
Hi,
I have read the #14 issue, i tried to did the same at switching position in the array but it doesnt working.
I need to switch position in the waypoint array. I try to create a new array and push into the waypoint but the route is not re drawing.
I have an array "tripDestinations" where i m saving the waypoints and the last record is the final destination. So i have to split the destinations after a change on the array.

Here is part of my code:

A function to switch dynamically destinations:

move(index: number, up: boolean) {
const newIndex = up ? index - 1 : index + 1;
while (index < 0) {
index += this.tripDestinations.length;
}
while (index < 0) {
index += this.tripDestinations.length;
}

if (newIndex >= this.tripDestinations.length) {
  let k = newIndex - this.tripDestinations.length + 1;
  while (k--) {
    this.tripDestinations.push(undefined);
  }
}
this.tripDestinations.splice(newIndex, 0, this.tripDestinations.splice(index, 1)[0]);
this.showRoute();
}

The function that i get the "final destination" and the waypoints:

showRoute(){
this.origin = { lat: this.latitudeOrigin, lng: this.longitudeOrigin };
const length = this.tripDestinations.length;
this.destination = { lat: this.tripDestinations[length - 1].latitude, lng: this.tripDestinations[length - 1].longitude };

  if (length > 1) {
    const waypoints: any[] = [];
    for (let index = 0; index < length - 1; index++) {
      waypoints.push({
        location: { lat: this.tripDestinations[index].latitude, lng: this.tripDestinations[index].longitude }
      });
      }
    this.waypoints = waypoints;
}
}
HTML:
<agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom">
<agm-direction [origin]="origin" [destination]="destination" [waypoints]="waypoints" [renderOptions]="renderOptions">

Example:
Original waypoint array:
[{"location":{"lat":-34.6048436,"lng":-58.40282109999998}},{"location":{"lat":-34.6173554,"lng":-58.38177689999998}}]

After using the "move()" function, i get this waypoint array in the showRoute():
[{"location":{"lat":-34.6173554,"lng":-58.38177689999998}},{"location":{"lat":-34.6048436,"lng":-58.40282109999998}}]

Thx in advance

**Comment by explooosion** [comment]
What does you MOVE function's params for?

Do you mean you want to create the direction from the waypoints which you store, and the last waypoint  will be set to the destination ?

Or could you please show me the full code for ts, html, thank you.

**Comment by Joni-89** [comment]
I thought that the order of the intermediate locations, it´s given by the order of the waypoint array.
So I made the function "move" to switch positions of the intermediate locations from the HTML.

From the HTML the user can choose multiples destinations wich are saving in the "tripDestinations" array. In the TS I´m getting the last postition in the array to use into the "destination" parameter in the "agm-direction". The other values in the array should be the intermediate locations.
I put two buttons in the HTML to move up or down the destinations (if the user wants to change the order of the intermediate locations or the final destination).
I need to re draw the route if I change the order of the intermediate locations (waypoint array). 
Example:
Orginal waypoint array: waypoint A(position 0), waypoint B(position 1), waypoint C(position 2) (the route should pass first from A then B then C) this is working fine, the "agm-direction" show the route correctly.
Suppose that the user made a mistake, and now he wants to go to waypoint C first. With the "move" method he should be able to modify the order of the destinations (change position in the array). 
The result is the following waypoint array: waypoint C (position 0), waypoint A (position 1), waypoint B (position 2) (the route should pass first from C then A then B) this is not working, the route is not re drawing.
I cant show the full code, I will put the part where the user can choose the origin, destination and waypoints.

HTML:
<div fxLayout="row" fxLayoutAlign="space-between center">
    <mat-form-field fxFlex="30">
        <input matInput type="text" formControlName="origin" (keydown.enter)="$event.preventDefault()" placeholder="Origen" autocorrect="off" autocapitalize="off" spellcheck="off" type="text" required #searchOrigin>
    </mat-form-field>
    <mat-form-field fxFlex="20">
        <input matInput tabindex="12" placeholder="Observaciones" type="text" formControlName="originObservation" autocomplete="off" />
    </mat-form-field>
</div>
<div fxLayout="row" fxLayoutAlign="space-between center">
    <mat-form-field fxFlex="30">
        <input matInput type="text" formControlName="destiny" (keydown.enter)="$event.preventDefault()" placeholder="Destino" autocorrect="off" autocapitalize="off" spellcheck="off" type="text" #searchDestiny>
    </mat-form-field>
    <mat-form-field fxFlex="20">
        <input matInput tabindex="14" placeholder="Observaciones" type="text" formControlName="destinyObservation" autocomplete="off" />
    </mat-form-field>
    <div fxFlex="10">
        <agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom">
            <agm-direction [origin]="origin" [destination]="destination" [waypoints]="waypoints" [renderOptions]="renderOptions">
            </agm-direction>
        </agm-map>
    </div>
</div>
<div>
    <mat-table [dataSource]="gridDestinations" class="table-list destinations-table-list">
        <ng-container matColumnDef="address">
            <mat-header-cell *matHeaderCellDef>Destino</mat-header-cell>
            <mat-cell *matCellDef="let destiny;">{{destiny.description}} {{destiny.observation}}
            </mat-cell>
        </ng-container>

        <ng-container matColumnDef="up">
            <mat-header-cell *matHeaderCellDef>Sube</mat-header-cell>
            <mat-cell *matCellDef="let destiny; let i = index;">
                <div style="display: flex; flex-direction: row; flex: 1 0 auto;">
                    <button class="custom-mat-button" mat-icon-button [disabled]="i === 0" style="margin-left: 30px; line-height: 32px; padding-left: 3px; margin-top: 5px;" (click)="move(i, true)">
                    <mat-icon>keyboard_arrow_up</mat-icon>
                </button>
                </div>
            </mat-cell>
        </ng-container>

        <ng-container matColumnDef="down">
            <mat-header-cell *matHeaderCellDef>Baja</mat-header-cell>
            <mat-cell *matCellDef="let destiny; let i = index;">
                <div style="display: flex; flex-direction: row; flex: 1 0 auto;">
                    <button class="custom-mat-button" mat-icon-button [disabled]="i === tripDestinations.length - 1" style="margin-left: 30px; line-height: 32px; padding-left: 3px; margin-top: 5px;" (click)="move(i, false)">
                    <mat-icon>keyboard_arrow_down</mat-icon>
                </button>
                </div>
            </mat-cell>
        </ng-container>

        <ng-container matColumnDef="actions">
            <mat-header-cell *matHeaderCellDef>Acciones</mat-header-cell>
            <mat-cell *matCellDef="let obj; let i = index;">

                <div style="display: flex; flex-direction: row; flex: 1 0 auto;">
                    <mat-list-item [matMenuTriggerFor]="actions">
                        <mat-icon mat-list-icon>more_vert</mat-icon>
                    </mat-list-item>
                </div>

                <mat-menu class="crud-list-action-menu" #actions="matMenu" [overlapTrigger]="false">
                    <span (mouseleave)="closeMenu()">
                    <button mat-menu-item class="crud-list-action-menu-button"
                        (click)="removeDestination(i); closeMenu(); $event.stopPropagation();">
                        Eliminar
                    </button>
                </span>
                </mat-menu>
            </mat-cell>
        </ng-container>

TS: 
// DESTINOS load Places Autocomplete
this.mapsAPILoader.load().then(() => {
    this.geoCoder = new google.maps.Geocoder();

    const autocomplete = new google.maps.places.Autocomplete(this.searchDestiny.nativeElement, {
      types: ['address']
    });
    autocomplete.addListener('place_changed', () => {
      this.ngZone.run(() => {
        // get the place result
        const place: google.maps.places.PlaceResult = autocomplete.getPlace();

        // verify result
        if (place.geometry === undefined || place.geometry === null) {
          return;
        }
        this.addNewDestination(place);
      });
    });
  });

  addNewDestination(place) {

      const newDestination = new TripsDestination();
      newDestination.deletedDateTime = new Date('1900-01-01');
      newDestination.createdBy = this.loginService.getFullname();
      newDestination.updatedBy = this.loginService.getFullname();
      newDestination.description = place.formatted_address;
      newDestination.observation = this.tripFormGroup.controls.destinyObservation.value;
      newDestination.id = 0;
      newDestination.latitude = place.geometry.location.lat();
      newDestination.longitude = place.geometry.location.lng();
      newDestination.statusId = 1;
      this.tripDestinations.push(newDestination);
      this.gridDestinations = new MatTableDataSource(this.tripDestinations);
      this.showRoute();
  }

  showRoute() {
    // Armo arrays para mostrar la ruta
    if (this.tripFormGroup.value.origin !== '' && this.tripDestinations.length > 0) {
      this.mapType = 'ruta';
      this.origin = { lat: this.latitudeOrigin, lng: this.longitudeOrigin }; // agm_direction: origin
      const length = this.tripDestinations.length;
      this.destination = { lat: this.tripDestinations[length - 1].latitude, lng: this.tripDestinations[length - 1].longitude }; // agm_direction: destination

      if (length > 1) {
        const waypoints: any[] = [];
        for (let index = 0; index < length - 1; index++) {
          waypoints.push({
            location: { lat: this.tripDestinations[index].latitude, lng: this.tripDestinations[index].longitude }
          });
          }
        this.waypoints = waypoints; // agm_direction: waypoints
      }
    }
  }

  move(index: number, up: boolean) {
    const newIndex = up ? index - 1 : index + 1;
    while (index < 0) {
      index += this.tripDestinations.length;
    }
    while (index < 0) {
      index += this.tripDestinations.length;
    }

    if (newIndex >= this.tripDestinations.length) {
      let k = newIndex - this.tripDestinations.length + 1;
      while (k--) {
        this.tripDestinations.push(undefined);
      }
    }
    this.tripDestinations.splice(newIndex, 0, this.tripDestinations.splice(index, 1)[0]);
    this.gridDestinations = new MatTableDataSource(this.tripDestinations);
    this.showRoute();
  }

Thx

**Comment by Joni-89** [comment]
Hi,
I found the solution, agm-direction use optimizeWaypoints in "TRUE" as default. The problem was not in the order of the waypoint array, google automatically sends the best route without considering the waypoint array order if is it "true".
So adding [optimizeWaypoints]="false", solved my problem.

Thx
