### ISSUE TITLE
Event click on agm-direction

### ISSUE THREAD

**Issue by SantiagoBco06** [explooosion/Agm-Direction#8]
Hello good afternoon, can you help me?

How can I use the event click on agm-direction?
I need to change the strokeColor of the selected route.

**Comment by explooosion** [comment]
Hola! good afternoon, I have upgraded a package. 📦
  
Thank you for your advice. 😃

![version](https://d25lcipzij17d.cloudfront.net/badge.svg?id=js&type=6&v=0.3.7&x2=0)

#### Install the latest version:
```bash
npm install --save agm-direction
```
or
```
npm install --save agm-direction@latest
```

#### Example:
You can check out the following example.

+ HTML

```html
<div class="map">
  <agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom">
    <agm-direction *ngIf="dir" [origin]="dir.origin" [destination]="dir.destination" [renderOptions]="dir.renderOptions"></agm-direction>
  </agm-map>
</div>

<button (click)="redColor()">RED</button>
<button (click)="greenColor()">BLUE</button>
```

+ TS
```ts
  lat: Number = 24.799448;
  lng: Number = 120.979021;
  zoom: Number = 15;

  dir = {
    origin: { lat: 24.799448, lng: 120.979021 },
    destination: { lat: 24.799108, lng: 120.970021 },
    renderOptions: {},
    visible: true,
  };

  constructor() { }

  public redColor() {
    this.dir.renderOptions = {
      polylineOptions: {
        strokeColor: '#f00',
        strokeOpacity: 0.6,
        strokeWeight: 5,
      }
    }
  }

  public greenColor() {
    this.dir.renderOptions = {
      polylineOptions: {
        strokeColor: '#0f0',
        strokeOpacity: 0.8,
        strokeWeight: 10,
      }
    }
  }
```

#### DEMO
![demo](https://user-images.githubusercontent.com/13682994/36884940-eac12c2e-1e1e-11e8-8b26-59dfd49d97f4.gif)

**Comment by SantiagoBco06** [comment]
Hi @explooosion, thank you for your prompt responses.

Is it possible to do to change the color without using external buttons?
For example, by clicking on the route?

`<div class="map">
  <agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom">
    <agm-direction *ngIf="dir" _**(click)="changeColor()"**_ [origin]="dir.origin" [destination]="dir.destination" [renderOptions]="dir.renderOptions"></agm-direction>
  </agm-map>
</div>
`

**Comment by explooosion** [comment]
[Draggable directions](https://developers.google.com/maps/documentation/javascript/examples/directions-draggable?hl=zh-tw)

It seems like the only event. 🙁
I only can handle the drag event.

```ts
directionsDisplay.addListener('directions_changed', function() {
       /** to do something */
});
```
