### ISSUE TITLE
Adding Support for Angular 9

### ISSUE THREAD

**Issue by srukshan98** [explooosion/Agm-Direction#93]
Please add the support for Angular 9.

The following Warning is coming after updating to Angular 9.

> Warning: Entry point 'agm-direction' contains deep imports into '{project_path}/node_modules/@agm/core/services/google-maps-types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by explooosion** [comment]
Please upgrade to 0.8.0

**Comment by srukshan98** [comment]
thank you
