### ISSUE TITLE
A Plain Box appears in google map between route

### ISSUE THREAD

**Issue by srukshan98** [explooosion/Agm-Direction#95]
![map issue](https://user-images.githubusercontent.com/32130720/86001666-d7cbb380-ba2c-11ea-838b-3b486bb40cb8.png)
The above Plain Block Appears randomly when showing route. Below is my code.
### HTML

```
<agm-map class="w-100 h-100" [fitBounds]="true" [streetViewControl]="false">
	<agm-direction *ngFor="let marker of directionList" [renderOptions]="renderOptions" [origin]="marker" [destination]="getAddressLocation()"></agm-direction>
	<agm-marker *ngFor="let marker of markerList" [agmFitBounds]="marker.isFocused"
		[latitude]="marker.lat" [longitude]="marker.lng" [markerClickable]="true" [markerDraggable]="false" [iconUrl]="marker.isPrimary ? null : {
			url: './assets/media/icons/secondary-pin.png',
			scaledSize: {
				width: 27,
				height: 43
			}
		}">
	</agm-marker>
</agm-map>
```
### TS
`
	renderOptions: any = {
		preserveViewport: true,
		suppressMarkers: true
	}
`

**Comment by explooosion** [comment]
Hi @srukshan98 
I don’t know what caused it. I can’t see the same error as you.  🧐
Are you still having problems if you only use agm-direction in agm-map?

**Comment by srukshan98** [comment]
> Are you still having problems if you only use agm-direction in agm-map?

It only occurs when directions are shown and I don't get any console or request errors. it only show when it is auto zoomed to show both points and only show when i scroll the background

**Comment by srukshan98** [comment]
This issue was because the container and it's parent both contained scroll bars which somehow effected the canvas in the map when directions were shown. 
It was fixed when one scroll bar was hidden
